mysite/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from . import views

urlpatterns = [
    path('auth/', obtain_auth_token),
    path('books/', views.BookListCreateAPIView.as_view()),
    path('books/<int:pk>/', views.BookDetailAPIView.as_view(), name='book-detail'),
    path('books/<int:pk>/update/', views.BookUpdateAPIView.as_view(), name='book-update'),
    path('books/<int:pk>/delete/', views.BookDeleteAPIView.as_view())]

mysite/myapp/urls.py
# myapp/urls.py
from django.urls import path
from .views import export_books, BookDeleteView, delete_all_books, BookListView, \
    BookDetailView, BookCreateView, BookUpdateView
from .viewsets import *

app_name = 'myapp'
urlpatterns = [
    path('book_list/', BookListView.as_view(), name='book_list'),
    path('detail/<int:id>', BookDetailView.as_view(), name='book_detail'),
    path('detail/<int:id>/delete', BookDeleteView.as_view(), name='book_delete'),
    path('update_book/<int:id>', BookUpdateView.as_view(), name='update_book'),
    path('add_book/', BookCreateView.as_view(), name='add_book'),
    path('delete_all_books/', delete_all_books, name='delete_all_books'),
    path('export_books/', export_books, name='export_books')
]

mysite/mysite/urls.py
# mysite/urls.py
from django.contrib import admin
from django.urls import include, path
import debug_toolbar
from pages.views import welcome_view

urlpatterns = [
    path('', welcome_view, name='home'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api/v2/', include('mysite.routers')),
    path("__debug__/", include(debug_toolbar.urls)),
    path('', include('myapp.urls', namespace='myapp')),
    path('search/', include('booksearch.urls'))]

mysite/myapp/models.py
# myapp/models.py
from _decimal import Decimal

from django.core.validators import MinValueValidator
from django.urls import reverse
from django.db import models
from booksearch.models import SearchableModel
from authors.models import Author


class Book(SearchableModel, models.Model):
    # objects = None
    title = models.CharField(max_length=200, blank=False, null=False)
    content = models.TextField(blank=True, null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=1000,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))], default=33.33
        # Enforce minimum value of 0.00 on DB level
    )

    def get_absolute_url(self):
        return reverse("myapp:book_detail", kwargs={"id": self.id})

    def __str__(self):
        return f"{self.title} Object ID: {self.id})"

    @classmethod
    def search(cls, query=None):
        """
        Get books with title with this query
        """
        return cls.objects.filter(title__icontains=query)

    @property
    def get_sale_price(self):
        float_val = float(self.price)
        return "%0.2f" % (float_val * 0.8)

mysite/myapp/forms.py
# myapp/forms.py

from _decimal import Decimal
from django import forms
from django.core.validators import MinValueValidator
from .models import Book


class BookForm(forms.ModelForm):
    """
    # Overrides ModelForm fields
    Working with Django Forms: https://docs.djangoproject.com/en/5.0/topics/forms/
    """
    title = forms.CharField(max_length=100, min_length=3,
                            label='Book Title',
                            widget=forms.TextInput(attrs={
                                'placeholder': 'book title here...'})
                            )
    price = forms.DecimalField(
        validators=[MinValueValidator(Decimal('10.00'))],
        # Enforce minimum value of 0.00 on DB level
        label='Book Price',initial=10.00
    )

    class Meta:
        model = Book
        fields = ['title', 'author', 'price']
        labels = {
            'author': 'Author Name',
        }

    # Recommendation:

    # If the customization involves simple attributes like min_length or label,
    # override the fields directly in the form. For more complex validation
    # logic, especially if it interacts with other fields,
    # centralize it in the clean_ method of the ModelForm. Here I combined those approaches.

    def clean_title(self):
        # Custom validation logic for the 'title' field
        title = self.cleaned_data['title']

        # Custom modification of the data
        modified_title = title.title()

        return modified_title

    def save(self, commit=True):
        # Override the save method to perform custom actions before saving

        # Perform additional data modification
        self.cleaned_data['title'] = self.clean_title()
        print(self.cleaned_data['price'])
        return super().save(commit)

mysite/myapp/views.py
# myapp/views
import csv
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, \
    DeleteView
from django.shortcuts import render, redirect, get_object_or_404

from .models import Book
from .forms import BookForm
from .serializers import BookSerializer
from authors.models import Author


class BookCreateView(CreateView):
    form_class = BookForm
    queryset = Book.objects.all()
    template_name = 'myapp/add_book.html'
    success_url = reverse_lazy('myapp:book_list')

    def form_valid(self, form):
        author_name = form.cleaned_data['author']
        print("****")
        author, created = Author.objects.get_or_create(name=author_name)
        print(author, created, "****")
        # Set the author for the book
        form.instance.author = author
        return super().form_valid(form)

    def get(self, request, *args, **kwargs):
        form = self.get_form()
        return self.render_to_response({'form': form, 'mode': 'Add'})


def delete_all_books(request):
    if request.method == 'POST':
        Book.objects.all().delete()
        return redirect('myapp:book_list')  # Redirect to the book list view
    return HttpResponse("Not available for now")


def export_books(request):
    if request.method == 'GET':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="books.csv"'

        writer = csv.writer(response)
        writer.writerow(['Title', 'Author'])

        books = Book.objects.all()
        for book in books:
            writer.writerow([book.title, book.author])
        return response
    else:
        return 'not supported'


def welcome_view(request):
    return render(request, 'myapp/welcome.html', {'name': 'Zack'})


class BookListView(ListView):
    queryset = Book.objects.all()
    template_name = 'myapp/book_list.html'
    context_object_name = 'objects'


class BookDetailView(DetailView):
    template_name = 'myapp/detail.html'
    context_object_name = 'object'

    def get_object(self, **kwargs):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)


class BookUpdateView(UpdateView):
    form_class = BookForm
    queryset = Book.objects.all()
    template_name = 'myapp/add_book.html'
    success_url = reverse_lazy('myapp:book_list')

    def form_valid(self, form):
        return super().form_valid(form)

    def get_initial(self):
        # Retrieve the existing values from the model instance
        initial = super().get_initial()
        book = self.get_object()
        initial['title'] = book.title
        initial['author'] = book.author
        initial['price'] = book.price
        return initial

    def get(self, request, *args, **kwargs):
        form = self.get_form()
        return self.render_to_response({'form': form, 'mode': 'Update'})

    def get_object(self, **kwargs):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)


def book_delete_view(request, id):
    if request.method == 'POST':
        book = get_object_or_404(Book, id=id)
        book.delete()
        return redirect('myapp:book_list')  # Redirect to the book list view
    else:
        return HttpResponse("Not available for now")


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'myapp/book_confirm_delete.html'
    success_url = reverse_lazy('myapp:book_list')
    def get_object(self, queryset=None):
        # Retrieve the book object to be deleted
        id_ = self.kwargs.get("id")
        return get_object_or_404(Book, id=id_)

    def delete(self, request, *args, **kwargs):
        # Override the delete method to perform additional actions if needed
        # For example, you can send a confirmation email before deleting
        print(666666666666666666666)
        return super().delete(request, *args, **kwargs)

mysite/myapp/templates/myapp/add_book.html
{% extends 'base.html' %}
{% block title %}Add book{% endblock %}

{% block content %}

<h1>{{mode}} a Book</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit" value="save">{{mode}} Book</button>
</form>
<br>
<!-- Add the button for deleting all books -->


<br>
<!-- Add a search form -->
<form method="GET" action="{% url 'search_view' model='book' app='myapp' %}">
    <label for="search_query">Search:</label>
    <input type="text" name="query" id="search_query">
    <button type="submit">Search books</button>
</form>

<br>

<form method="GET" action="{% url 'search_view' model='author' app='authors'  %}">
    <input type="text" name="query" id="search_query2">
    <button type="submit">Search authors</button>
</form>


<a href="{% url 'myapp:book_list' %}">Back to Book List</a>
{% endblock %}

mysite/myapp/templates/myapp/book_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Confirmation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 100px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            color: #333;
        }
        p {
            text-align: center;
            margin-top: 20px;
            color: #666;
        }
        .button-container {
            text-align: center;
            margin-top: 30px;
        }
        .button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Delete Confirmation</h1>
        <p>Are you sure you want to delete this item?</p>
        <div class="button-container">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="button">Delete</button>
            </form>
        </div>
    </div>
</body>
</html>

mysite/myapp/templates/myapp/book_list.html
{% extends 'base.html' %}
{% block title %}Book List{% endblock %}

{% block content %}
<h1>Book List</h1>
<ul>
    {% if objects%}
    {% for instance in objects %}
    <li>
        <strong>{{ forloop.counter }}:</strong>
        Book ID: {{ instance.id }},
        <a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a>
        by {{ instance.author }}
    </li>
    <br>
    {% endfor %}
    {% else %}
    No books for now
    {%endif%}
</ul>
<a href="{% url 'myapp:add_book' %}">Back to add book</a>
<br>
<form method="POST" action="{% url 'myapp:delete_all_books' %}">
    {% csrf_token %}
    <button type="submit"
            onclick="return confirm('Are you sure you want to delete all books?');"
            style="background-color: red; color: white;">Delete All Books
    </button>

</form>
<h2>Export Books</h2>
<p>Click the button below to export the list of books to a CSV file.</p>

<a href="{% url 'myapp:export_books' %}" class="btn btn-primary">Export
    Books</a>
{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'base.html' %}
{% block title %}Book details{% endblock %}

{% block content %}
<h1> Book detail</h1>
<h2>{{object.title}} costs {{object.price}}</h2>
<form method="POST" action="{% url 'myapp:book_delete' object.id %}">
    {% csrf_token %}
    <button type="submit"
            onclick="return confirm('Are you sure you want to delete this book?');"
            style="background-color: red; color: white;">Delete this book
    </button>

</form>
<a href="{% url 'myapp:book_list' %}">Back to Book List</a>

{% endblock %}

mysite/myapp/templates/myapp/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to My Django App</title>

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #333;
        }

        p {
            color: #555;
            font-size: 18px;
            text-align: center;
        }
    </style>
</head>
<body>

    <h1>Welcome to My Django App</h1>
    {% if name%}
    <h1> {{name }}</h1>
    {%endif%}
    <p>Enjoy your Django journey!</p>
</body>
</html>